# This is a basic workflow to help you get started with Actions

name: 08-DeviceTwinUpdate-pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - '08-DeviceTwinUpdate/**'
  pull_request:
    paths:
      - '08-DeviceTwinUpdate/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: infinitecoding/platformio-for-ci:latest
      options: -u root 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      env:
        BlobStorageRootUrl: https://iotdemotschissler.blob.core.windows.net/firmwareupdates
        CurrentFirmwareVersion: v$GITHUB_RUN_NUMBER
        IoTHubConnectionString: HostName=IoTHub-tschissler.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=FecNNDaJpTDn0Bv1goAWu3QdyIpBD7HQ1B9+HA7JpD0=
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Replace tokens
        # You may pin to the exact commit or the version.
        # uses: cschleiden/replace-tokens@121d9153eda2951d490e9f724a67ff095ab4c4f7
        uses: cschleiden/replace-tokens@v1.0
        with:
          tokenPrefix: <
          tokenSuffix: >
          files: "**/*.cpp"

      # Runs a single command using the runners shell
      - name: Compile Firmware
        run: platformio run -e esp32dev -d ./08-DeviceTwinUpdate/

