name: 08-DeviceTwinUpdate-pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - '08-DeviceTwinUpdate/**'
  pull_request:
    paths:
      - '08-DeviceTwinUpdate/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: infinitecoding/platformio-for-ci:latest
      options: -u root 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Replace tokens
        # You may pin to the exact commit or the version.
        # uses: cschleiden/replace-tokens@121d9153eda2951d490e9f724a67ff095ab4c4f7
        uses: cschleiden/replace-tokens@v1.0
        with:
          tokenPrefix: <
          tokenSuffix: >
          files: "**/*.cpp"
        env:
          BlobStorageRootUrl: https://iotdemotschissler.blob.core.windows.net/firmwareupdates
          CurrentFirmwareVersion: "v${GITHUB_RUN_NUMBER}"
          IoTHubConnectionString: HostName=IoTHub-tschissler.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=FecNNDaJpTDn0Bv1goAWu3QdyIpBD7HQ1B9+HA7JpD0=
          
      - name: Compile Firmware
        run: platformio run -e esp32dev -d ./08-DeviceTwinUpdate/
        
      - name: Upload Firmware
        uses: actions/upload-artifact@v2.2.3
        with:
          name: firmware
          path: "**/firmware.bin"
          if-no-files-found: error
          retention-days: 1
          
  PushToBlob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "Using Run Number ${GITHUB_RUN_NUMBER}"
      - run: echo "Using Run Number " ${GITHUB_RUN_NUMBER}
      - run: echo "Using Run Number {{github.run_number}}"
      
      - name: Download Firmware
        uses: actions/download-artifact@v2.0.9
        with:
          # Artifact name
          name: firmware

      - name: Azure Blob Upload ${GITHUB_RUN_NUMBER}
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        with:
          connection_string: DefaultEndpointsProtocol=https;AccountName=iotdemotschissler;AccountKey=/U66uH+yigYKgY8JPWAMTTYO+CFPfsO9RTQGMcRImx7Ssb+qsr0iqjU5UZTQmkJd6p1NiaqQFnXCpTYtm0k4zg==;BlobEndpoint=https://iotdemotschissler.blob.core.windows.net/;QueueEndpoint=https://iotdemotschissler.queue.core.windows.net/;TableEndpoint=https://iotdemotschissler.table.core.windows.net/;FileEndpoint=https://iotdemotschissler.file.core.windows.net/;
          container_name: firmwareupdates
          source_folder: 08-DeviceTwinUpdate/.pio/build/esp32dev
          destination_folder: "v${GITHUB_RUN_NUMBER}"
          fail_if_source_empty: true
